services:
  backend:
    build:
      context: ./backend
    container_name: mangatrackr-backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: mangatrackr-frontend
    ports:
      - "80:80"
    restart: unless-stopped
